export const LISTAR_USUARIOS = "LISTAR_USUARIOS";
export const MOSTRAR_USUARIO = "MOSTRAR_USUARIO";
export const ELIMINAR_USUARIO = "ELIMINAR_USUARIO";
export const CREAR_USUARIO = "CREAR_USUARIO";
export const EDITAR_USUARIO = "EDITAR_USUARIO";
export const BUSCAR_USUARIO = "BUSCAR_USUARIO";
